mongodb:
  hostname: easytravel-mongodb
  container_name: mongodb
  image: "dynatrace/easytravel-mongodb"
  ports:
  - 27017
  - 28017

backend:
  hostname: easytravel-backend
  container_name: backend
  image: "dynatrace/easytravel-backend"
  ports:
  - 8080
  links:
  - mongodb
  environment:
    ET_DATABASE_LOCATION: "mongodb:27017"

frontend:
  hostname: easytravel-frontend
  container_name: frontend
  image: "dynatrace/easytravel-frontend"
  ports:
  - 8080
  links:
  - backend
  - mongodb
  environment:
    ET_BACKEND_URL: "http://backend:8080"

www:
  hostname: easytravel-www
  container_name: www
  image: "dynatrace/easytravel-nginx"
  ports:
  - 80
  links:
  - frontend

loadgen:
  container_name: loadgen
  image: "dynatrace/easytravel-loadgen"
  links:
  - www
